server:
  port: 8080

spring:
  application:
    name: service-getway

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://xfyx:xfyx@localhost:8081/eureka/