server:
  port: 8072

spring:
  application:
    name: service-app

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://xfyx:xfyx@localhost:8081/eureka/